### PR TITLE
fix: escape defaultMessage properly, fixes #1158

### LINKED ISSUE #1158: Escaping curly braces does not work in production mode if the message has no format parameters
### Step to reproduce
Say you have a translations file that contains the following:
```JSON
{
  "example": "The string \\{token\\} is replaced with the actual token."
}
```

And you render this string in your React app like so:
```JS
props.intl.formatMessage({ id: "example" })
```

Then all is well in development mode and the string that gets inserted into the page is
```
The string {token} is replaced with the actual token.
```

However, once you run in production mode (`NODE_ENV === 'production'`), the string gets inserted with the backslash still present and the page renders as follows:
```
The string \{token\} is replaced with the actual token.
```

It looks like the root cause of this bug was introduced in the following commit:
https://github.com/yahoo/react-intl/commit/44168fb883f0419f0ddbbc3c154d127ca3d8c1f3. The relevant snippt is:
```JS
    if (!hasValues && process.env.NODE_ENV === 'production') {
        return message || defaultMessage || id;
    }
```
which skips formatting, which then means the correctly escaped curly is never unescaped.

| Executable | Version |
| ---: | :--- |
| react-intl | 2.4.0 |
| react | 16.4.1 |
| npm | 5.6.0 |
| node | v9.11.2 |

### PR DESCRIPTION
**Pull request by longlho**

### CODE REVIEW

File: test/unit/format.js [hunk 1]
```diff
@@ -672,6 +672,21 @@ RangeError: Invalid unit argument`
       formatMessage = f.formatMessage.bind(null, config, state);
     });
 
+    ['Hello, World!\\{foo\\}', '\\ud83d\\udc04'].forEach(msg =>
+      it(`should render escaped msg ${msg} properly in production`, () => {
+        process.env.NODE_ENV = 'production';
```
Comment (redonkulus) [inline test/unit/format.js]: Should we unset this after the test?

Comment (longlho) [reply test/unit/format.js]: that's done in `afterEach` already :)
